name: GitHub Classroom Workflow

on:
  - push
  - workflow_dispatch

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - uses: actions/checkout@v4
      - uses: education/autograding@v1

  linting-check:
    name: Linting and Formatting Check
    runs-on: ubuntu-latest
    timeout-minutes: 2

    env:
      lab_number: 9

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Format with Black
        id: formatting_check
        run: |
          black "lab$lab_number.py" --check --preview --line-length=120
        continue-on-error: true

      - name: Lint with Flake8
        id: bonus_pep8_linter_check_flake8
        run: |
          flake8 "lab$lab_number.py"
          echo "::warning title=Lint Checks with Flake8::Click the above link to view Linting logs"
        continue-on-error: true